apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: net-utils
  labels:
    jira-key: JSC
    language: Dockerfile
  annotations:
    backstage.io/source-location: url:https://github.com/wandera/net-utils
spec:
  type: infrastructure
  lifecycle: production
  owner: zircon
  system: Connect
  description: Docker image for net-utils
  
